version: '3'

services:

  
      
      
  elasticsearch:
    container_name: elasticsearch
    #build:
    #  context: elasticsearch/
    image: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    #networks:
    #  - elk
  
  kibana:
    #build:
    #  context: kibana/
    container_name: kibana
    image: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    #networks:
    #  - elk
    depends_on:
      - elasticsearch

  web:
    container_name: web
    restart: always
    build: ./flask
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "8000"
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    #networks:
    #  - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch      
  
    
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/static:/app/static
    links:
      - web:web
    ports:
      - "80:80"
      
      
  
   
  
volumes:
  elasticsearch:  
  

networks:
  elk:
    driver: bridge  
