version: '3'

services:

  web:
    container_name: web
    restart: always
    build: ./flask
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    expose:
      - "8000"
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
     
  
    
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/flaskapp/static:/app/static
    links:
      - web:web
    ports:
      - "80:80"
      
      
  
   
